name: bccm_player
description: ExoPlayer/AVPlayer via platform views, with cast, PiP, background audio, audio selection, etc.
version: 1.0.0
documentation: https://bcc-code.github.io/bccm-player/
repository: https://github.com/bcc-code/bccm_player

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_plugin_android_lifecycle: ^2.0.9
  flutter_state_notifier: ^0.7.3
  flutter_svg: ^2.0.2
  flutter_web_plugins:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  js: ^0.6.5
  meta: ^1.9.1
  plugin_platform_interface: ^2.0.2
  riverpod: ^2.2.0
  state_notifier: ^0.7.2+1
  universal_io: ^2.0.4
  wakelock_plus: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^9.0.1
  build_runner: ^2.3.3
  mockito: ^5.4.2

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: media.bcc.bccm_player
        pluginClass: BccmPlayerPlugin
      ios:
        pluginClass: BccmPlayerPlugin
      web:
        pluginClass: BccmPlayerWeb
        fileName: bccm_player_web.dart
